from __future__ import annotations

NUM_JOINTS = 7

DEFAULT_TCP_HOST = "192.168.10.21"

MIN_VELOCITY = 0.0
MAX_VELOCITY = 20.0
DEFAULT_VELOCITY = 0.5

MIN_ACCELERATION = 0.0
MAX_ACCELERATION = 20.0
DEFAULT_ACCELERATION = 1.0

DEFAULT_MOVE_TIMEOUT = 20.0
DEFAULT_MOVE_TOLERANCE = 0.035

MOVE_L_MAX_MAX_VELOCITY = 0.4
MOVE_L_DEFAULT_MAX_VELOCITY = 0.05
MOVE_L_MAX_MAX_ANGULAR_VELOCITY = 3.0
MOVE_L_DEFAULT_MAX_ANGULAR_VELOCITY = 0.3

MOVE_L_MAX_ACCELERATION = 1.0
MOVE_L_DEFAULT_ACCELERATION = 0.1
MOVE_L_MAX_ANGULAR_ACCELERATION = 1.0
MOVE_L_DEFAULT_ANGULAR_ACCELERATION = 0.1
